// frontend/src/components/Terminal.tsx
import { useEffect, useState, type FormEvent } from 'react';
import { useBluetooth } from '@/context/BluetoothContext';
import { terminalEventBus } from '@/lib/terminalEventBus';

type LogEntry = {
	id: number;
	type: string;
	message: string;
};

let logId = 0;

export function Terminal() {
	const bluetoothTerminal = useBluetooth();
	const [logs, setLogs] = useState<LogEntry[]>([]);
	const [inputValue, setInputValue] = useState('');

	useEffect(() => {
		return terminalEventBus.subscribe((event) => {
			if (event.type === 'data' && event.direction === 'in') {
				setLogs((current) => [
					...current,
					{ id: ++logId, type: 'in', message: event.data },
				]);
			}

			if (event.type === 'log') {
				setLogs((current) => [
					...current,
					{ id: ++logId, type: '', message: event.message },
				]);
			}

			if (event.type === 'error') {
				setLogs((current) => [
					...current,
					{ id: ++logId, type: 'error', message: event.message },
				]);
			}
		});
	}, []);

	function send(data: string) {
		bluetoothTerminal
			.send(data)
			.then(() => {
				terminalEventBus.emit({ type: 'data', data, direction: 'out' });
				setLogs((current) => [
					...current,
					{ id: ++logId, type: 'out', message: data },
				]);
			})
			.catch((error: Error) => {
				terminalEventBus.emit({ type: 'error', message: String(error) });
				setLogs((current) => [
					...current,
					{ id: ++logId, type: 'error', message: String(error) },
				]);
			});
	}

	function handleSubmit(event: FormEvent<HTMLFormElement>) {
		event.preventDefault();

		if (!inputValue) {
			return;
		}

		send(inputValue);
		setInputValue('');
	}

	return (
		<>
			<div className="flex-grow overflow-auto border-y border-black/10 py-1">
				<ul>
					{logs.map((log) => (
						<li key={log.id}>
							<div className={log.type}>{log.message}</div>
						</li>
					))}
				</ul>
			</div>

			<form id="send-form" className="send-form flex w-full" onSubmit={handleSubmit}>
				<input
					id="input"
					type="text"
					aria-label="Input"
					autoComplete="off"
					placeholder="Type something to send..."
					value={inputValue}
					onChange={(event) => setInputValue(event.target.value)}
					className="flex-1"
				/>

				<button type="submit" aria-label="Send">
					<i className="material-icons">send</i>
				</button>
			</form>
		</>
	);
}

// src/lib/Terminal.svelte
<script lang="ts">
	import { getContext } from 'svelte';
	import type { BluetoothTerminal } from './BluetoothTerminal';

	const bluetoothTerminal = getContext<BluetoothTerminal>('bluetoothTerminal');

	let logs: {type?: string, message: string}[] = [];

	function logToTerminal(message: string, type = ''){
		console.log('logs', logs);
		logs.push({type, message});
		logs = logs;
	};

	bluetoothTerminal.receive = function(data) {
		console.log('data', data);
		logToTerminal(data, 'in');
	};


	// Override default log method to output messages to the terminal and console.
	bluetoothTerminal._log = function(...messages) {
		// We can't use `super._log()` here.
		messages.forEach((message) => {
			logToTerminal(message);
			console.log(message); // eslint-disable-line no-console
		});
	};
	
	let inputValue = '';

	const send = (data) => {
		bluetoothTerminal.send(data)
			.then(() => logToTerminal(data, 'out'))
			.catch((error) => logToTerminal(error));
	};

	function handleSumbit(event) {
		event.preventDefault();

		send(inputValue);

		inputValue = '';
	}
</script>

<div class="terminal">
	{#each logs as log (log.message)}
	<!-- {#each logs as { type, message }, i} -->
		<li>
			<div class="{log.type}">
				{log.message}
			</div>
		</li>
	{/each}
</div>
<form id="send-form" class="send-form" on:submit={handleSumbit}>

	<input 
		id="input" 
		type="text" 
		aria-label="Input" 
		autocomplete="off" 
		placeholder="Type something to send..."
		bind:value={inputValue}
	>

	<button type="submit" aria-label="Send">
		<i class="material-icons">send</i>
	</button>
</form>

<style>
	.terminal {
		border: 1px solid rgba(0, 0, 0, 0.12);
		border-width: 1px 0;
		flex-grow: 1;
		overflow: auto;
		padding: 4px 0;
	}
</style>
